version: "3.5"

volumes:
  mws-install-home: {}
  mws-sum-home:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mws-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
    project_internal_network:
      external: false
services:
  mws:
    image: centos-sag-osgi-helper
    container_name: mws
    hostname: mws
    networks:
      - project_internal_network
    volumes:
      - mws-temp:/tmp/
      - mws-install-home:/opt/sag/products/
      - mws-sum-home:/opt/sag/sum/
      - ${WM_LAB_HOME}/common/mount/extra:/opt/sag/mnt/extra/
      - ${WM_LAB_HOME}/common/mount/runs/:/opt/sag/mnt/runs/
      - ${WM_LAB_HOME}/common/config/secret/:/opt/sag/mnt/secret/
      - ${WM_LAB_HOME}/linux/scripts/:/opt/sag/mnt/scripts/
      - ${SAG_PRODUCT_IMAGE}:/opt/sag/mnt/wm-install-files/products.zip
      - ${SAG_FIXES_IMAGE}:/opt/sag/mnt/wm-install-files/fixes.zip
      - ${SAG_INSTALLER_BIN}:/opt/sag/mnt/wm-install-files/installer.bin
      - ${SAG_UPD_MGR_BIN}:/opt/sag/mnt/wm-install-files/sum-bootstrap.bin
      - ${SAG_LIC_BR}:/opt/sag/mnt/wm-install-files/licenses/br.xml
    environment:
      - MWS_DB_TYPE=mysqlce
      - MWS_DB_URL=jdbc:mysql://mysql:3306/webmethods?useSSL=false
      - MWS_DB_USERNAME=webmethods
      - MWS_DB_PASSWORD=webmethods
      - MWS_NODE_NAME=mws
    ports:
      - "${MWS_MAIN_PORT}:8585"
    entrypoint: /opt/sag/mnt/scripts/entrypoints/mws.bash