version: "3.5"

volumes:
  mysql_data: {}
networks:
    project_internal_network:
      external: false
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    hostname: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project_internal_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webmethods
      - MYSQL_USER=webmethods
      - MYSQL_PASSWORD=webmethods
      - MYSQL_LOG_CONSOLE=true
#      ports:
#        - "3306:3306"
    command: >
      --sql-mode="PIPES_AS_CONCAT,IGNORE_SPACE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS"
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max_allowed_packet=24M
      --default-storage-engine=innodb
      --lower_case_table_names=1
      --innodb_buffer_pool_size=5G
      --innodb_log_file_size=80M
