version: "3.5"

services:
  centos-wm-install-helper-base:
    image: centos-wm-install-helper
    container_name: wm-install-helper-mws
    hostname: wm-install-helper-mws
    volumes:
      - ${SAG_WM_INSTALL_BASE_DIR}/mount/:/mnt/wm-install-base-mount/
      - ${SAG_PRODUCT_IMAGE}:/mnt/wm-install-files/products.zip
      - ${SAG_INSTALLER_BIN}:/mnt/wm-install-files/installer.bin
      - ${SAG_UPD_MGR_BIN}:/mnt/wm-install-files/sum-bootstrap.bin
      - ${BASE_LIBS}/:/mnt/wm-install-base-libs/
      - ./mount/:/mnt/wm-install-mws-mount/
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: tail -f /dev/null
