version: "3.5"

networks:
    n1:
      external: false
services:
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    networks:
      - n1
    ports:
      - "${SAG_W_ADMINER_PORT}:8080"
