version: "3.5"

networks:
    n1:
      external: false
services:
  mysql:
    image: kristophjunge/test-saml-idp
    container_name: ${SAG_W_PJ_NAME}-saml-idp1
    hostname: saml-idp1
    networks:
      - n1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webmethods
      - MYSQL_USER=webmethods
      - MYSQL_PASSWORD=webmethods
      - MYSQL_LOG_CONSOLE=true
    ports:
      - "${SAG_W_SAML_IDP1_CLEAR_PORT}:8080"
      - "${SAG_W_SAML_IDP1_SSL_PORT}:8080"
    command: >
      --sql-mode="PIPES_AS_CONCAT,IGNORE_SPACE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS"
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max_allowed_packet=128M
      --default-storage-engine=innodb
      --lower_case_table_names=1
      --innodb_buffer_pool_size=5G
      --innodb_log_file_size=80M
