version: "3.5"

networks:
    n1:
      external: false
services:
  mysql:
    image: kristophjunge/test-saml-idp
    container_name: ${H_WMLAB_PJ_NAME}-idp
    hostname: idp
    networks:
      n1:
        aliases:
          - idp
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://${H_WMLAB_MWS_HOSTNAME}:8585
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://${H_WMLAB_MWS_HOSTNAME}:8585/what-here?
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://${H_WMLAB_MWS_HOSTNAME}:8585/what-here?
    ports:
      - "${H_WMLAB_SAML_IDP1_CLEAR_PORT}:8080"
      - "${H_WMLAB_SAML_IDP1_SSL_PORT}:8443"
