version: "3.5"

volumes:
  mysqlce_data: {}
networks:
    n1:
      external: false
services:
  mysql:
    image: mysql/mysql-server:5.7
    #container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_DB_HOSTNAME}
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_DB_HOSTNAME} 
    hostname: ${H_WMLAB_DB_HOSTNAME}
    volumes:
      - mysqlce_data:/var/lib/mysql
    networks:
      n1:
        aliases:
          - ${H_WMLAB_DB_HOSTNAME}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webmethods
      - MYSQL_USER=webmethods
      - MYSQL_PASSWORD=webmethods
      - MYSQL_LOG_CONSOLE=true
    ports:
      - "${H_WMLAB_MYSQL_HOST_PORT}:3306"
    command: >
      --sql-mode="PIPES_AS_CONCAT,IGNORE_SPACE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS"
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max_allowed_packet=128M
      --default-storage-engine=innodb
      --lower_case_table_names=1
      --innodb_buffer_pool_size=5G
      --innodb_log_file_size=80M
